# Generated by Django 5.2.1 on 2025-06-03 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_alter_lead_assignee_alter_lead_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='in_queue',
            field=models.BooleanField(default=False, verbose_name='В очереди'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('interested', 'Успешно'), ('converted', 'Перезвон'), ('canceled', 'Не актуально')], default='new', max_length=20),
        ),
    ]
